# Generated by Django 4.1.3 on 2022-11-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
