# Generated by Django 4.1.3 on 2022-11-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.class')),
            ],
        ),
    ]
