# Generated by Django 4.1.3 on 2022-11-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_class',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='student_id',
        ),
    ]
